### ISSUE TITLE
10.1.5-beta1 retail: deprecated classic function used

### ISSUE THREAD

**Issue by speedwaystar** [tullamods/tullaRange#27]
6x tullaRange/updater.classic.lua:307: hooksecurefunc(): ActionBarButtonEventsFrame_RegisterFrame is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@tullaRange/updater.classic.lua"]:307: in function `Enable'
[string "@tullaRange/tullaRange.lua"]:55: in function `func'
[string "@tullaRange/tullaRange.lua"]:20: in function <tullaRange/tullaRange.lua:16>

**Comment by Tuller** [comment]
The beta doesn't work on 10.1, just on the 10.1.5 PTR

**Comment by speedwaystar** [comment]
ah, gotcha
