### ISSUE TITLE
Small Error at Login with latest Beta 2 version

### ISSUE THREAD

**Issue by Galthariel** [tullamods/tullaRange#29]
Here is the error.

```
1x tullaRange/updater.classic.lua:308: hooksecurefunc(): ActionBarButtonEventsFrame_RegisterFrame is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@tullaRange/updater.classic.lua"]:308: in function `Enable'
[string "@tullaRange/tullaRange.lua"]:55: in function `func'
[string "@tullaRange/tullaRange.lua"]:20: in function <tullaRange/tullaRange.lua:16>

Locals:
```

**Comment by Tuller** [comment]
Are you playing on a 10.1 realm? The beta version only works on 10.1.5+

**Comment by Galthariel** [comment]
That explains and yes, playing Retail and not PTR. Super sorry.
